name: flutter_exoplayer
description: A flutter plugin to play audio files using the Java ExoPlayer library.
version: 0.5.5
homepage: https://github.com/danielR2001/flutter_exoplayer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  uuid: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.8
flutter:
  plugin:
    androidPackage: danielr2001.audioplayer
    pluginClass: AudioPlayerPlugin
